language: R
warnings_are_errors: true

sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libboost-all-dev
  - libnlopt-dev
  - libeigen3-dev
  - libcurl4-openssl-dev
  - libxml2-dev

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-6.3 -y
  - sudo apt-get install gfortran-6.3 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6.3 100
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6.3 100
  
repos:
  CRAN: http://cran.rstudio.com
